In [ ]:
import pandas as pd

df = pd.read_csv("carros\\base_carros.txt", sep=";")
df

---

# Parte 1 — Conhecendo os dados

## 1. Primeiros registros

Carregue o arquivo CSV utilizando Pandas e apresente os **5 primeiros registros**.


### Conclusão

> O que você conseguiu identificar inicialmente sobre a organização dos dados?

**Resposta: Os dados estão organiziados em colunas (cada uma = uma informação do carro) e linhas (cada uma = um carro), separados por ";", bem estruturados e consistentes.**

---

In [12]:
df = pd.read_csv("Carros/base_carros.txt", sep=";")
df.head()

     UF   Município     Marca Modelo Ano Fabricação Veículo CRV  Qtd. Veículos
0  ACRE  ACRELANDIA     AGRALE/13000                       2009            1.0
1  ACRE  ACRELANDIA      AGRALE/1800                       1989            1.0
2  ACRE  ACRELANDIA      AGRALE/1800                       1990            1.0
3  ACRE  ACRELANDIA  AGRALE/1800D RD                       1989            1.0
4  ACRE  ACRELANDIA  AGRALE/1800D RD                       1990            2.0

---

## 2. Dimensões do DataFrame

Descubra:

- Quantas **linhas** existem;
- Quantas **colunas** existem.

In [13]:
linhas,colunas = df.shape

print("linhas;",linhas)
print("Colunas",colunas)

linhas; 22690877
Colunas 5

---

## 3. Estrutura dos dados

Identifique o **tipo de dado (****`dtype`****)** de cada coluna.

### Conclusão

> Existem colunas numéricas? Existem colunas contendo texto?

**Resposta: Existe colunas numéricas e colunas de texto no conjunto de dados**

---

In [ ]:
#CONVERTENDO A COLUNA DE ANO DE FABRICAÇÃO PARA NÚMERO

df["Ano Fabricação Veículo CRV"] = pd.to_numeric(df["Ano Fabricação Veículo CRV"], errors='coerce')
df["Ano Fabricação Veículo CRV"] = df["Ano Fabricação Veículo CRV"].astype("Int64")

In [42]:
df.dtypes

UF                                str
Município                         str
Marca Modelo                      str
Ano Fabricação Veículo CRV      Int64
Qtd. Veículos                 float64
dtype: object

---

## 4. Selecionando informações

Crie uma consulta que apresente somente:

- `MUNICIPIO`
- `MARCA MODELO`
- `QTD. VEICULOS`

In [24]:
df[["Município","Marca Modelo","Qtd. Veículos"]]

           Município            Marca Modelo  Qtd. Veículos
0         ACRELANDIA            AGRALE/13000            1.0
1         ACRELANDIA             AGRALE/1800            1.0
2         ACRELANDIA             AGRALE/1800            1.0
3         ACRELANDIA         AGRALE/1800D RD            1.0
4         ACRELANDIA         AGRALE/1800D RD            2.0
...              ...                     ...            ...
22690872     XAMBIOA  YAMAHA/YS150 FAZER SED            1.0
22690873     XAMBIOA  YAMAHA/YS150 FAZER SED            1.0
22690874     XAMBIOA  YAMAHA/YS150 FAZER SED            1.0
22690875     XAMBIOA  YAMAHA/YS150 FAZER SED            1.0
22690876     XAMBIOA      YAMAHA/YZF R15 ABS            1.0

[22690877 rows x 3 columns]

---

## 5. Estados presentes na base

Descubra quais **UFs diferentes** aparecem na base de dados.

Depois descubra quantas UFs diferentes foram encontradas.

In [37]:
df["UF"].unique()
df["UF"].nunique()

30

# Parte 2 — Filtrando e ordenando dados

## 6. Veículos de São Paulo

Crie um novo DataFrame contendo **somente registros do estado de São Paulo (SP)**.

In [26]:
df_sp = df[df["Município"] == "SÃO PAULO"]
df_sp

Empty DataFrame
Columns: [UF, Município, Marca Modelo, Ano Fabricação Veículo CRV, Qtd. Veículos]
Index: []

## 7. Veículos recentes

Encontre somente registros de veículos cujo **ano de fabricação seja igual ou superior a 2020**.

In [43]:
filtro_2020 = df["Ano Fabricação Veículo CRV"] >= 2020

df[filtro_2020].size

19956910

---

## 8. Registros com grande quantidade de veículos

Encontre registros cuja coluna `QTD. VEICULOS` seja **maior que 1.000**.

### Evidência

Apresente alguns registros encontrados:

```text
```

---

In [44]:
df_grande = df[df["Qtd. Veículos"] > 1000]
df_grande.head()

,UF,Município,Marca Modelo,Ano Fabricação Veículo CRV,Qtd. Veículos
37745,ACRE,RIO BRANCO,HONDA/CG 125 FAN,2008,1457.0
37746,ACRE,RIO BRANCO,HONDA/CG 125 FAN ES,2009,1242.0
37747,ACRE,RIO BRANCO,HONDA/CG 125 FAN ES,2010,1031.0
37756,ACRE,RIO BRANCO,HONDA/CG 125 FAN KS,2009,1179.0
37757,ACRE,RIO BRANCO,HONDA/CG 125 FAN KS,2010,1376.0

---

## 9. Maiores registros da base

Ordene o DataFrame pela coluna `QTD. VEICULOS` e apresente os **10 maiores registros**.

### Conclusão

> O que esses registros representam? Existe algum município, modelo ou ano que chamou sua atenção?

**Resposta: São os 10 maiores da frota: municípios grandes , modelos populares e anos recenetes se destacam**

---

In [45]:
df_maiores = df.sort_values("Qtd. Veículos", ascending=False).head(10)
df_maiores

,UF,Município,Marca Modelo,Ano Fabricação Veículo CRV,Qtd. Veículos
9739613,PARANA,CURITIBA,MOTTU/SPORT 110I,2025,85730.0
22443299,Sem Informação,Sem Informação,HONDA/POP100,<NA>,78640.0
22443293,Sem Informação,Sem Informação,HONDA/POP 110I,<NA>,70758.0
9739614,PARANA,CURITIBA,MOTTU/SPORT 110I,2026,66521.0
22455064,Sem Informação,Sem Informação,SHINERAY/50Q,<NA>,61580.0
22443294,Sem Informação,Sem Informação,HONDA/POP 110I ES,<NA>,51824.0
5471799,MINAS GERAIS,BELO HORIZONTE,FIAT/ARGO DRIVE 1.0,2025,46271.0
22443107,Sem Informação,Sem Informação,HONDA/CG 160 FAN,<NA>,44956.0
22445239,Sem Informação,Sem Informação,I/HAOJIAN AVELLOZ AZ1,<NA>,43591.0
22456643,Sem Informação,Sem Informação,TRAXX/JL50 Q2,<NA>,40848.0

---

## 10. Quantidade total de veículos

Descubra quantos veículos são representados por **toda a base de dados**.

> Atenção: não queremos descobrir quantas linhas existem. Utilize a coluna `QTD. VEICULOS`.

### Conclusão

> Explique por que a quantidade de linhas do DataFrame é diferente da quantidade total de veículos.


**Resposta: Linha = grupo,não veículo. Soma a coluna para ter o total real**

---

In [46]:
total = df["Qtd. Veículos"].sum()
total

np.float64(135374097.0)

---

# Parte 3 — Agrupando informações

## 11. Frota por estado

Descubra a quantidade total de veículos registrada em **cada UF**.

Apresente parte do resultado: Agrupa por UF e soma a Qtd, veículos mostra o total de vrículos por estado

```text
```

---

In [48]:
frota_por_uf = df.groupby("UF")["Qtd. Veículos"].sum()
frota_por_uf.head()

UF
ACRE         401028.0
ALAGOAS     1290570.0
AMAPA        293783.0
AMAZONAS    1328112.0
BAHIA       5906191.0
Name: Qtd. Veículos, dtype: float64


---

## 12. Estados com as maiores frotas

Utilizando os dados da questão anterior, descubra as **5 UFs com maior quantidade de veículos**.


| Posição | UF | Quantidade de veículos |
| ------: | -- | ---------------------: |
|      1º |    |                        |
|      2º |    |                        |
|      3º |    |                        |
|      4º |    |                        |
|      5º |    |                        |

### Conclusão

> O resultado foi o que você esperava? O que é possível concluir observando essas cinco UFs?

**Resposta: Os maiores são os estados mais populosos e ricos. A frota segue o tamanho da população**

---

In [52]:
maiores_frotas = (
    df.groupby("UF")["Qtd. Veículos"].sum().sort_values(ascending=False).head(5).reset_index()

)
maiores_frotas

                  UF  Qtd. Veículos
0          SAO PAULO     35973347.0
1       MINAS GERAIS     14834984.0
2             PARANA      9955512.0
3  RIO GRANDE DO SUL      8644077.0
4     RIO DE JANEIRO      8449199.0

------ CONSULTA -------

In [35]:
df_sp = df[df.Município == "SAO PAULO"]

df_sp.sort_values("Qtd. Veículos", ascending=False)

,UF,Município,Marca Modelo,Ano Fabricação Veículo CRV,Qtd. Veículos
21661075,SAO PAULO,SAO PAULO,VW/POLO TRACK MA,2024,25031.0
21635915,SAO PAULO,SAO PAULO,MOTTU/SPORT 110I,2024,19912.0
21589784,SAO PAULO,SAO PAULO,FIAT/UNO ELECTRONIC,1994,17656.0
21661076,SAO PAULO,SAO PAULO,VW/POLO TRACK MA,2025,16559.0
21598693,SAO PAULO,SAO PAULO,HONDA/CG 125 FAN,2008,15603.0
...,...,...,...,...,...
21582031,SAO PAULO,SAO PAULO,ADAX,1991,1.0
21582065,SAO PAULO,SAO PAULO,AGRALE/14000,2012,1.0
21625433,SAO PAULO,SAO PAULO,IMP/M.BENZ 280 S,1985,1.0
21625403,SAO PAULO,SAO PAULO,IMP/M.BENZ 250,1966,1.0
21625405,SAO PAULO,SAO PAULO,IMP/M.BENZ 250,1969,1.0

In [ ]:
df_rj = df[df.Município == "RIO DE JANEIRO"]

df_rj.sort_values("Qtd. Veículos", ascending=False)

In [ ]:
## VERIFICANDO QUAL MARCA E MODELO MAIS EXISTE EM SÃO PAULO (SEM CONSIDERAR ANO)


df_sp = df[df.Município == "SAO PAULO"]


# df_sp.sort_values("Qtd. Veículos", ascending=False)
marcamodelo_sp = df_sp.groupby("Marca Modelo")["Qtd. Veículos"].sum()
marcamodelo_sp.sort_values(ascending=False).head(5)

In [ ]:
df['Ano Fabricação Veículo CRV'] = pd.to_numeric(df['Ano Fabricação Veículo CRV'], erros='ConnectionResetError')
df['Ano Fabricação Veículo CRV'] = df['Ano fabricação Veículo CRV'].astype()